services:
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/bot/src
      - ./prisma:/bot/prisma

networks:
  default:
    name: postgres