services:
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/bot/src
      - ./prisma:/bot/prisma

  studio:
    build:
      context: .
    depends_on: [bot, postgres]
    env_file:
      - .env
    working_dir: /bot
    volumes:
      - ./prisma:/bot/prisma
    entrypoint: ["yarn", "exec", "prisma", "studio"]
    ports:
      - 5555

networks:
  default:
    name: postgres